[package]
authors = ["Maximilian Krüger <kruemaxi@gmail.com>"]
description = ""
documentation = "https://snd.github.io/onmf/onmf/index.html"
homepage = "https://github.com/snd/onmf"
keywords = ["machine learning"]
license = "MIT OR Apache-2.0"
name = "onmf"
readme = "README.md"
repository = "https://github.com/snd/onmf.git"
version = "0.1.0"

[dependencies]
image = "0.6.1"
nalgebra = "0.4.0"
num = "0.1.30"
quick-error = "0.2.1"
rand = "0.3.12"
